title: Pr1malbyt3s
remote_theme: pmarsceill/just-the-docs
heading_anchors: false
markdown: kramdown
webrick:
  headers:
    Strict-Transport-Security: max-age=31556952; includeSubdomains
exclude: ["README.md", "CNAME"]
